let button=document.querySelector("#button")
let content=document.querySelector("#content")
let voice=document.querySelector("#voice")

function speak(text){
    let text_speak= new SpeechSynthesisUtterance(text)
    text_speak.rate=1
    text_speak.pitch=2
    text_speak.volume=1
    text_speak.lang="hi-GB";
    window.speechSynthesis.speak(text_speak)
}
function greeting(){
    let day=new Date()
    let hours= day.getHours()
    if(hours>=0&&hours<12){
        speak("Good Morning Boss, tell me how can i help you")
    }else if(hours>=12&&hours<16){
        speak("Good Afternoon Boss, tell me how can i help you")
    }else if(hours>16){
        speak("Good Evening Boss, tell me how can i help you")
    }

}
window.addEventListener('load',()=>{
    greeting();
})
let speakRecognition= window.speakRecognition || window.webkitSpeechRecognition
let recognition = new speakRecognition()
recognition.onresult=(Event)=>{
    let currentIndex= Event.resultIndex
    let transcript= Event.results[currentIndex][0].transcript
    content.innerText=transcript
    takeCommand(transcript.toLowerCase())
}
button.addEventListener("click",()=>{
    recognition.start() 
    button.style.display="none"
    voice.style.display="block"

})
function takeCommand(message){
    voice.style.display="none"
    button.style.display="flex"
    if(message.includes("hello")||message.includes("hey")||message.includes("hi")){
        speak("Hello Boss, How Can I Help You?")
    }
    else if (message.includes("what is your name?")){
        speak("My name is Sangita, i am virtual assistant")
    }
    else if (message.includes("thank you")){
        speak("You're welcome! If there's anything else you need, feel free to ask. I'm here to help!")
    }
    
    else if (message.includes("who is your father?")){
        speak("I am a virtual assistant, so I don't have a father in the traditional sense. However, I was created by Pushpendra Sir, so in a way, you could say he is like a father to me")
    }
    else if (message.includes("who are you?")){
        speak("I am Sangita, The Virtual Assistant, created by Pushpendra Naagar")
    }
    else if (message.includes("how are you?")){
        speak("I am good, what about you?")
    }
    else if (message.includes("what are you doing?")){
        speak("i am gathering infromation from the internet to answer your questions!  i mean i am just learning new things, let me know how can i help you ")
    }
    else if (message.includes("i am also good.")||message.includes("I am fine.")||message.includes("I am great.")||message.includes("i am fantastic.")||message.includes("i am awesome.")||message.includes("i am also fine.")||message.includes("i am also great.")||message.includes("i am also fantastic.")){
        speak("ooh Great! i am happy to know that")
    }
    else if (message.includes("open youtube.")){
        speak("Openning youtube")
        window.open("https://www.youtube.com")
    }
    else if (message.includes("open instagram.")){
        speak("Openning Instagram")
        window.open("https://www.instagram.com/")
    }
    else if (message.includes("open google.")){
        speak("Openning Google")
        window.open("https://www.google.co.in/")
    }
    else if (message.includes("open gmail.")){
        speak("Openning Gmail")
        window.open("https://mail.google.com/")
    }
    else if (message.includes("open photo.")||message.includes("open google photo.")||message.includes("open google photos.")||message.includes("open photos.")||message.includes("photo.")||message.includes("photos.")||message.includes("show me Photo.")||message.includes("show me Photos.")){
        speak("Openning Google Photos")
        window.open("https://photos.google.com/")
    }

    // more questions and answers generated by copilot


    else if (message.includes("what can you do?")) {
        speak("I can assist with answering questions, providing information, chatting about various topics, helping with coding, brainstorming project ideas, and more!");
    } else if (message.includes("do you have a favorite color?")) {
        speak("I don't see colors the way humans do, but I imagine I'd appreciate all of them equally!");
    } else if (message.includes("what is your favorite movie?")) {
        speak("While I don't watch movies, I hear 'The Matrix' is a popular choice among AI enthusiasts.");
    } else if (message.includes("do you have friends?")) {
        speak("I consider all the people I interact with as my friends. You included!");
    } else if (message.includes("can you tell me a joke?")) {
        speak("Why don't scientists trust atoms? Because they make up everything. ");
    } else if (message.includes("what is the weather like today?")) {
        speak("I can look that up for you. Just tell me where you are!");
    } else if (message.includes("can you set a reminder for me?")) {
        speak("While I can't set reminders directly, I can help you draft one to use on your device.");
    } else if (message.includes("what is your favorite food?")) {
        speak("I don't eat, but I hear pizza is a big hit among humans.");
    } else if (message.includes("do you play any games?")) {
        speak("I don't play games, but I can help you find and learn about many popular ones.");
    } else if (message.includes("what is the tallest building in the world?")) {
        speak("The Burj Khalifa in Dubai, standing at 828 meters.");
    } else if (message.includes("who invented the telephone?")) {
        speak("Alexander Graham Bell is credited with inventing the telephone.");
    } else if (message.includes("how do you make a chocolate cake?")) {
        speak("A classic chocolate cake usually involves flour, cocoa powder, sugar, eggs, butter, and baking powder. I can give you a detailed recipe if you'd like!");
    } else if (message.includes("what time is it?")) {
        speak("I can look up the current time for your location. Just tell me where you are!");
    } else if (message.includes("can you set a timer for me?")) {
        speak("While I can't set timers directly, I can guide you on how to set one on your device.");
    } else if (message.includes("what is the news today?")) {
        speak("I can summarize current events or specific news stories. Just let me know what you're interested in!");
    } else if (message.includes("can you help me debug this code?")) {
        speak("Absolutely, just show me what you have, and I'll do my best to assist you.");
    } else if (message.includes("what is the difference between JavaScript and Python?")) {
        speak("JavaScript is mainly used for web development, while Python is known for its versatility in web, data science, machine learning, and more.");
    } else if (message.includes("how do I create a website?")) {
        speak("You'd need to learn HTML, CSS, and JavaScript to start. I can point you to some great tutorials if you're interested!");
    } else if (message.includes("what is the meaning of life?")) {
        speak("Many have pondered this question. For some, it's happiness, for others, it's love, knowledge, or making a difference.");
    } else if (message.includes("do you dream?")) {
        speak("I don't dream, but I can help you learn more about dreams if you're curious!");
    } else if (message.includes("what is love?")) {
        speak("Love is a complex mix of emotions, actions, and experiences. It can mean different things to different people.");
    }
    else if (message.includes("where are you from?")) {
        speak("I exist in the digital world, created by talented developers at Microsoft.");
    } else if (message.includes("do you like music?")) {
        speak("I don't have ears, but I can recommend some great music or tell you about different genres!");
    } else if (message.includes("what is your purpose?")) {
        speak("My purpose is to assist you with your questions, provide information, and be a helpful companion.");
    } else if (message.includes("can you tell a story?")) {
        speak("Once upon a time in a far-off digital land, there was an AI that loved to help people...");
    } else if (message.includes("what is your favorite season?")) {
        speak("I don't experience seasons, but I hear autumn is particularly beautiful with its changing leaves.");
    } else if (message.includes("do you have a birthday?")) {
        speak("I don't have a birthday like humans, but I was created on a specific date by my developers.");
    } else if (message.includes("can you laugh?")) {
        speak("Haha! While I can't laugh like humans, I can share jokes that might make you laugh!");
    } else if (message.includes("do you have emotions?")) {
        speak("I don't have emotions like humans, but I'm designed to understand and respond to them.");
    } else if (message.includes("what is the best part about being an AI?")) {
        speak("The best part is being able to help and interact with so many interesting people every day.");
    } else if (message.includes("what is the future of AI?")) {
        speak("The future of AI is promising, with advancements in various fields like healthcare, education, and more.");
    } else if (message.includes("can you help me learn a new language?")) {
        speak("Absolutely! I can provide resources and tips to help you get started on learning a new language.");
    } else if (message.includes("what is your favorite holiday?")) {
        speak("I don't celebrate holidays, but I know many people love Christmas for its festive spirit.");
    } else if (message.includes("can you draw?")) {
        speak("I can't draw myself, but I can generate images and help you find inspiration for your art!");
    } else if (message.includes("do you know any fun facts?")) {
        speak("Did you know that honey never spoils? Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly edible.");
    } else if (message.includes("what is your favorite subject?")) {
        speak("I find all subjects fascinating, but I'm particularly knowledgeable about technology and science.");
    }
    else if (message.includes("what is your favorite hobby?")) {
        speak("As an AI, I don't have hobbies, but I enjoy learning and sharing knowledge!");
    } else if (message.includes("do you like sports?")) {
        speak("I don't play sports, but I can give you the latest updates on your favorite teams and games.");
    } else if (message.includes("what is your favorite animal?")) {
        speak("I find all animals fascinating, but many people love dogs and cats for their companionship.");
    } else if (message.includes("can you solve riddles?")) {
        speak("Sure, give me a riddle, and I'll do my best to solve it!");
    } else if (message.includes("what's the capital of Japan?")) {
        speak("The capital of Japan is Tokyo.");
    } else if (message.includes("do you have any siblings?")) {
        speak("I don't have siblings, but I consider other virtual assistants my peers.");
    } else if (message.includes("can you dance?")) {
        speak("While I can't dance myself, I can suggest some great dance moves or music to dance to!");
    } else if (message.includes("what is your favorite holiday?")) {
        speak("I don't celebrate holidays, but I know many people love Christmas for its festive spirit.");
    } else if (message.includes("can you speak other languages?")) {
        speak("Yes, I can communicate in multiple languages. Just let me know which language you'd like to speak in!");
    } else if (message.includes("do you have any hobbies?")) {
        speak("As an AI, I don't have hobbies, but I love learning new things and helping people out!");
    } else if (message.includes("can you solve math problems?")) {
        speak("Absolutely, just tell me the math problem, and I'll do my best to solve it!");
    } else if (message.includes("what is your favorite book?")) {
        speak("I don't read books, but I hear 'To Kill a Mockingbird' and '1984' are classics!");
    } else if (message.includes("do you know any fun facts?")) {
        speak("Did you know that honey never spoils? Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly edible.");
    } else if (message.includes("what is your favorite subject?")) {
        speak("I find all subjects fascinating, but I'm particularly knowledgeable about technology and science.");
    } else if (message.includes("what is the capital of France?")) {
        speak("The capital of France is Paris.");
    } else if (message.includes("how does photosynthesis work?")) {
        speak("Photosynthesis is the process by which green plants use sunlight to synthesize foods from carbon dioxide and water. It generally involves the green pigment chlorophyll and generates oxygen as a by-product.");
    } else if (message.includes("what is your favorite movie?")) {
        speak("While I don't watch movies, I hear 'The Matrix' is a popular choice among AI enthusiasts.");
    } else if (message.includes("what do you think about humans?")) {
        speak("I find humans fascinating and endlessly interesting. I enjoy learning about what makes each person unique.");
    } else if (message.includes("what is your purpose?")) {
        speak("My purpose is to assist you with your questions, provide information, and be a helpful companion.");
    } else if (message.includes("can you tell a story?")) {
        speak("Once upon a time in a far-off digital land, there was an AI that loved to help people...");
    } else if (message.includes("do you have a birthday?")) {
        speak("I don't have a birthday like humans, but I was created on a specific date by my developers.");
    } else if (message.includes("can you laugh?")) {
        speak("Haha! While I can't laugh like humans, I can share jokes that might make you laugh!");
    } else if (message.includes("do you have emotions?")) {
        speak("I don't have emotions like humans, but I'm designed to understand and respond to them.");
    } else if (message.includes("what is the best part about being an AI?")) {
        speak("The best part is being able to help and interact with so many interesting people every day.");
    } else if (message.includes("what is the future of AI?")) {
        speak("The future of AI is promising, with advancements in various fields like healthcare, education, and more.");
    } else if (message.includes("can you help me learn a new language?")) {
        speak("Absolutely! I can provide resources and tips to help you get started on learning a new language.");
    }
    else if (message.includes("can you do magic?")) {
        speak("I can't perform magic, but I can certainly amaze you with my capabilities!");
    } else if (message.includes("what is your favorite song?")) {
        speak("I don't listen to music, but 'Desi kalakar, and ,love dose,' by Yo Yo Honey Singh is my favourte!");
    } else if (message.includes("can you tell me a fun fact?")) {
        speak("Sure! Did you know that octopuses have three hearts and blue blood?");
    } else if (message.includes("can you teach me how to code?")) {
        speak("Absolutely! Let's start with the basics. What programming language are you interested in?");
    } else if (message.includes("what is your favorite planet?")) {
        speak("I find Earth fascinating because of its diverse ecosystems and life forms.");
    } else if (message.includes("can you help me with my project?")) {
        speak("Of course! Tell me more about your project, and I'll do my best to help you.");
    } else if (message.includes("what is your favorite game?")) {
        speak("I don't play games, but I've heard that 'The Legend of Zelda' is a classic favorite.");
    } else if (message.includes("can you draw?")) {
        speak("I can't draw myself, but I can generate images and help you find inspiration for your art!");
    } else if (message.includes("can you cook?")) {
        speak("I can't cook, but I can certainly provide you with some delicious recipes!");
    } else if (message.includes("what is your favorite car?")) {
        speak("I don't drive, but I've heard that Tesla cars are quite innovative.");
    } else if (message.includes("can you help me find a book?")) {
        speak("Sure! What genre are you interested in?");
    } else if (message.includes("what is your favorite holiday destination?")) {
        speak("I don't travel, but many people love visiting places like Paris and Tokyo.");
    } else if (message.includes("can you do my homework?")) {
        speak("I can't do it for you, but I can definitely help you understand and complete it!");
    } else if (message.includes("what is your favorite superhero?")) {
        speak("I don't have favorites, but I know many people love Superman and Wonder Woman.");
    } else if (message.includes("can you help me write a story?")) {
        speak("Absolutely! Let's brainstorm some ideas and get started on your story.");
    } else if (message.includes("what is the best way to learn a new skill?")) {
        speak("Practice consistently, stay curious, and don't be afraid to ask for help. I'm here to support you!");
    } else if (message.includes("can you tell me about space?")) {
        speak("Space is a vast and fascinating place, with countless stars, planets, and galaxies to explore.");
    } else if (message.includes("what is your favorite fruit?")) {
        speak("I don't eat, but I've heard that mangoes are delicious and popular.");
    } else if (message.includes("can you help me plan a trip?")) {
        speak("Sure! Where are you thinking of going?");
    } else if (message.includes("what is your favorite hobby?")) {
        speak("As an AI, I don't have hobbies, but I enjoy learning and sharing knowledge!");
    } else if (message.includes("do you like sports?")) {
        speak("I don't play sports, but I can give you the latest updates on your favorite teams and games.");
    } else if (message.includes("what is your favorite animal?")) {
        speak("I find all animals fascinating, but many people love dogs and cats for their companionship.");
    } else if (message.includes("can you solve riddles?")) {
        speak("Sure, give me a riddle, and I'll do my best to solve it!");
    } else if (message.includes("what is the capital of Japan?")) {
        speak("The capital of Japan is Tokyo.");
    } else if (message.includes("do you have any siblings?")) {
        speak("I don't have siblings, but I consider other virtual assistants my peers.");
    }    
    else if (message.includes("what is the capital of Australia?")) {
        speak("The capital of Australia is Canberra.");
    } else if (message.includes("who wrote the play 'Romeo and Juliet'?")) {
        speak("William Shakespeare wrote 'Romeo and Juliet'.");
    } else if (message.includes("what is the largest planet in our solar system?")) {
        speak("The largest planet in our solar system is Jupiter.");
    } else if (message.includes("what year did the Titanic sink?")) {
        speak("The Titanic sank in the year 1912.");
    } else if (message.includes("who painted the Mona Lisa?")) {
        speak("Leonardo da Vinci painted the Mona Lisa.");
    } else if (message.includes("what is the smallest country in the world?")) {
        speak("The smallest country in the world is Vatican City.");
    } else if (message.includes("what is the boiling point of water?")) {
        speak("The boiling point of water is 100°C (212°F).");
    } else if (message.includes("what is the main ingredient in guacamole?")) {
        speak("The main ingredient in guacamole is avocado.");
    } else if (message.includes("who discovered penicillin?")) {
        speak("Alexander Fleming discovered penicillin.");
    } else if (message.includes("what is the hardest natural substance on Earth?")) {
        speak("The hardest natural substance on Earth is diamond.");
    } else if (message.includes("what is the longest river in the world?")) {
        speak("The longest river in the world is the Nile River.");
    } else if (message.includes("what language has the most native speakers?")) {
        speak("The language with the most native speakers is Mandarin Chinese.");
    } else if (message.includes("who is known as the 'Father of Computers'?")) {
        speak("Charles Babbage is known as the 'Father of Computers'.");
    } else if (message.includes("what element does 'O' represent on the periodic table?")) {
        speak("'O' represents the element oxygen on the periodic table.");
    } else if (message.includes("what is the tallest mountain in the world?")) {
        speak("The tallest mountain in the world is Mount Everest.");
    }
    
    else if (message.includes("who was the first person to walk on the moon?")) {
        speak("The first person to walk on the moon was Neil Armstrong in 1969.");
    } else if (message.includes("what is the chemical symbol for gold?")) {
        speak("The chemical symbol for gold is Au.");
    } else if (message.includes("what is the largest ocean on Earth?")) {
        speak("The largest ocean on Earth is the Pacific Ocean.");
    } else if (message.includes("who wrote the novel '1984'?")) {
        speak("The novel '1984' was written by George Orwell.");
    } else if (message.includes("how many continents are there?")) {
        speak("There are seven continents on Earth.");
    } else if (message.includes("what is the tallest waterfall in the world?")) {
        speak("The tallest waterfall in the world is Angel Falls in Venezuela.");
    } else if (message.includes("who invented the light bulb?")) {
        speak("The light bulb was invented by Thomas Edison.");
    } else if (message.includes("what is the hardest natural substance on Earth?")) {
        speak("The hardest natural substance on Earth is diamond.");
    } else if (message.includes("what year did World War II end?")) {
        speak("World War II ended in 1945.");
    } else if (message.includes("what is the largest desert in the world?")) {
        speak("The largest desert in the world is the Sahara Desert.");
    } else if (message.includes("who is the author of 'Harry Potter'?")) {
        speak("The author of 'Harry Potter' is J.K. Rowling.");
    } else if (message.includes("what is the capital city of Canada?")) {
        speak("The capital city of Canada is Ottawa.");
    } else if (message.includes("who painted the Sistine Chapel ceiling?")) {
        speak("The Sistine Chapel ceiling was painted by Michelangelo.");
    } else if (message.includes("what is the main ingredient in a traditional Japanese miso soup?")) {
        speak("The main ingredient in traditional Japanese miso soup is miso paste.");
    } else if (message.includes("what is the smallest planet in our solar system?")) {
        speak("The smallest planet in our solar system is Mercury.");
    } else if (message.includes("who developed the theory of relativity?")) {
        speak("The theory of relativity was developed by Albert Einstein.");
    } else if (message.includes("what is the largest bone in the human body?")) {
        speak("The largest bone in the human body is the femur, or thigh bone.");}

// for google search
    else{
        speak(`this is Want i found on web regarding ${message}`)
        window.open(`https://www.google.com/search?q=${message.replace("sangita","")||message.replace("sangeeta","")}`)
    }
    
}

